### PR TITLE
Postfix spf dkim

### PR DESCRIPTION
**Pull request by alexfornuto**

### CODE REVIEW

**Comment by alexfornuto** [comment]
@tknarr ping?

**Comment by tknarr** [comment]
Finished commenting, will review this PR for any additional changes. Sorry, I got sick and then got pulled off onto other things for a couple of days.

**Comment by alexfornuto** [comment]
No worries!

**Comment by tknarr** [comment]
I also hacked up a quick Python program to make dealing with the files from opendkim-genkey a bit easier. I'm trying to draw a line about new material though, to avoid making a moving target. On my side I'm using Atom set to soft tabs and 4-character tab stops, hopefully no more indentation problems.

**Pull request merged**
